# Generated by Django 5.0.4 on 2024-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dimension',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
